name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies for Function
      run: dotnet restore ./BoomTime
    - name: Build Function
      run: dotnet build ./BoomTime --no-restore /p:DeployOnBuild=true /p:DeployTarget=Package;CreatePackageOnPublish=true
    - name: Package Function
      shell: pwsh
      run: |
        Compress-Archive -Path .\BoomTime\bin\Debug\netcoreapp3.1\Publish\ -DestinationPath .\package.zip
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies for Deploy
      run: dotnet restore ./BoomTime.Deploy
    - name: Build Deploy
      run: dotnet build ./BoomTime.Deploy --no-restore --configuration Release
    - name: Copy package to Deploy
      shell: pwsh
      run: |
        Copy-Item .\package.zip -Destination .\BoomTime.Deploy\bin\Release\netcoreapp5.0\package.zip
    - name: Az login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - name: Depoy to Azure
      env: 
        twilioSid: ${{ secrets.TWILIOSID }}
        twilioToken: ${{ secrets.TWILIOTOKEN }}
        twilioFrom: ${{ secrets.TWILIOFROM }}
        twilioTo: ${{ secrets.TWILIOTO }}
      run: dotnet ./BoomTime.Deploy/bin/Release/netcoreapp5.0/BoomTime.Deploy.dll
        
